[mypy]
python_version = 3.11
warn_return_any = True
disallow_untyped_defs = True
no_implicit_optional = True
check_untyped_defs = True
pretty = True
mypy_path = src
packages = hermes_bilevel

[mypy-yaml.*]
ignore_missing_imports = True
