name: Security/config concern
description: Security/config concern
title: "[Security/config concern] "
labels: []
body:
  - type: textarea
    id: details
    attributes:
      label: Details
      description: What happened?
    validations:
      required: true
